# Generated by Django 2.2.1 on 2019-07-12 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=17)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('transaction_uid', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('bonus_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('withdrawals', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('withdrawal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_code', models.IntegerField(blank=True, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=17)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('transaction_uid', models.CharField(blank=True, max_length=20, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Wallet')),
            ],
        ),
    ]
