# Generated by Django 2.2.1 on 2019-08-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190712_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Wallet'),
        ),
    ]
