# Generated by Django 2.2.1 on 2019-08-22 18:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190802_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='request_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 8, 22, 18, 8, 48, 186319, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
