# Generated by Django 2.2.1 on 2019-08-23 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_deposit_request_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='request_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 8, 23, 14, 10, 33, 2079, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
