# Generated by Django 2.2.1 on 2019-08-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_withdrawal_request_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
