# Generated by Django 2.2.1 on 2019-08-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190823_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='request_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
