# Generated by Django 2.2.1 on 2019-08-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190830_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bank_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
