# Generated by Django 2.2.1 on 2019-08-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190831_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
