# Generated by Django 2.2.1 on 2019-07-12 21:35

from django.db import migrations, models
import django.utils.timezone
import utilities.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('profile_image', models.ImageField(default='uploads/profile/no-img.png', upload_to=utilities.helper.Helper.user_upload_file_name)),
                ('username', models.CharField(error_messages={'blank': 'Please enter username.'}, max_length=100, null=True, verbose_name='Username')),
                ('email', models.EmailField(error_messages={'required': 'Please provide email address.', 'unique': 'A user with this email address already exist.'}, max_length=40, null=True, unique=True)),
                ('phone', models.CharField(error_messages={'required': 'Please provide your phone number.', 'unique': 'A user with this phone number already exist.'}, max_length=20, unique=True)),
                ('calling_code', models.IntegerField()),
                ('first_name', models.CharField(blank=True, error_messages={'required': 'Please enter your first name.'}, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, error_messages={'required': 'Please enter your last name.'}, max_length=50, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=30, null=True)),
                ('referred', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
