# Generated by Django 2.2.1 on 2019-07-31 13:02

from django.db import migrations, models
import utilities.helper


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190731_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='calling_code',
            field=models.IntegerField(default=234),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='uploads/profile/no-img.png', upload_to=utilities.helper.Helper.user_upload_file_name),
        ),
    ]
