# Generated by Django 2.2.1 on 2019-10-01 22:53

from django.db import migrations, models
import utilities.helper


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20191001_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesetting',
            old_name='trial_start',
            new_name='trial_ending',
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to=utilities.helper.Helper.slider_image_upload),
        ),
    ]
