# Generated by Django 2.2.1 on 2019-08-10 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_auto_20190712_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
