# Generated by Django 2.2.1 on 2019-08-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='title',
        ),
        migrations.AddField(
            model_name='support',
            name='phone',
            field=models.CharField(blank=True, error_messages={'blank': 'Please enter your phone number', 'required': 'Please enter your phone number'}, max_length=120),
        ),
    ]
