# Generated by Django 2.2.1 on 2019-11-07 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stack', '0017_auto_20191104_1924'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, db_index=True)),
                ('team_a_score', models.CharField(blank=True, max_length=10, null=True)),
                ('team_b_score', models.CharField(blank=True, max_length=10, null=True)),
                ('team_a_corner_kicks', models.CharField(blank=True, max_length=10, null=True)),
                ('team_b_corner_kicks', models.CharField(blank=True, max_length=10, null=True)),
                ('team_a_cards', models.CharField(blank=True, max_length=10, null=True)),
                ('team_b_cards', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('open', 'OPEN'), ('canceled', 'CANCELED'), ('resulted', 'RESULTED')], default='open', max_length=10)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='stack.Team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='stack.Team')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('team_a_score', models.CharField(blank=True, max_length=10, null=True)),
                ('team_b_score', models.CharField(blank=True, max_length=10, null=True)),
                ('team_a_corner_kicks', models.CharField(blank=True, max_length=10, null=True)),
                ('team_b_corner_kicks', models.CharField(blank=True, max_length=10, null=True)),
                ('team_a_cards', models.CharField(blank=True, max_length=10, null=True)),
                ('team_b_cards', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('won', 'WON'), ('lose', 'LOSE')], max_length=10, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
