# Generated by Django 2.2.1 on 2019-11-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0004_auto_20191111_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='team_a_cards',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='team a cards'),
        ),
        migrations.AlterField(
            model_name='question',
            name='team_a_corner_kicks',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='team a corner kicks'),
        ),
        migrations.AlterField(
            model_name='question',
            name='team_a_score',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='team a score'),
        ),
        migrations.AlterField(
            model_name='question',
            name='team_b_cards',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='team b cards'),
        ),
        migrations.AlterField(
            model_name='question',
            name='team_b_corner_kicks',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='team b corner kicks'),
        ),
        migrations.AlterField(
            model_name='question',
            name='team_b_score',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='team b score'),
        ),
    ]
