# Generated by Django 2.2.1 on 2019-11-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0005_auto_20191111_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='team_a_logo',
            field=models.CharField(default='nothing', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='team_b_logo',
            field=models.CharField(default='nothing', max_length=1000),
            preserve_default=False,
        ),
    ]
