# Generated by Django 2.2.1 on 2019-11-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0006_auto_20191112_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='event',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
