# Generated by Django 2.2.1 on 2019-11-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0007_question_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
