# Generated by Django 2.2.1 on 2019-11-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0008_auto_20191114_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='team_a_cards',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='team_b_cards',
        ),
        migrations.RemoveField(
            model_name='question',
            name='team_a_cards',
        ),
        migrations.RemoveField(
            model_name='question',
            name='team_b_cards',
        ),
        migrations.AddField(
            model_name='question',
            name='total_cards',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='total cards'),
        ),
    ]
