# Generated by Django 2.2.1 on 2019-11-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0010_attempt_total_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='team_a_corner_kicks',
            new_name='total_corner_kicks',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='team_b_corner_kicks',
        ),
        migrations.RemoveField(
            model_name='question',
            name='team_a_corner_kicks',
        ),
        migrations.RemoveField(
            model_name='question',
            name='team_b_corner_kicks',
        ),
        migrations.AddField(
            model_name='question',
            name='total_corner_kicks',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='total corner kicks'),
        ),
    ]
