# Generated by Django 2.2.1 on 2019-07-12 21:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('game_over', models.BooleanField(default=False)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('schedule_start_time', models.DateTimeField(blank=True, null=True)),
                ('winners', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=100000.0, max_digits=17)),
                ('amount_available', models.DecimalField(decimal_places=2, default=100000.0, max_digits=17)),
                ('space', models.IntegerField(default=10)),
                ('decision', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_win', models.BooleanField(default=False)),
                ('away_team_win', models.BooleanField(default=False)),
                ('both_even', models.BooleanField(default=False)),
                ('under_two_five', models.BooleanField(default=False)),
                ('over_two_five', models.BooleanField(default=False)),
                ('win', models.BooleanField(default=False)),
                ('settled', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=150)),
                ('away_team', models.CharField(max_length=150)),
                ('home_team_score', models.IntegerField(default=0)),
                ('away_team_score', models.IntegerField(default=0)),
                ('home_team_odd', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('away_team_odd', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('under_two_five', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('over_two_five', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('even_odd', models.CharField(max_length=20)),
                ('match_start_time', models.DateTimeField(blank=True, null=True)),
                ('match_ending_time', models.DateTimeField(blank=True, null=True)),
                ('clubs_history', models.TextField(blank=True, null=True)),
                ('role', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RafflePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RaffleWinners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WeekEndRaffle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raffle_ending', models.DateTimeField(blank=True, null=True)),
                ('raffle_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('events', models.ManyToManyField(to='stack.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_token', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('amount_won', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('game_fate', models.IntegerField(default=0)),
                ('played_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('today', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='today', to='stack.ActiveGame')),
            ],
        ),
    ]
