# Generated by Django 2.2.1 on 2019-07-12 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slip_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rafflewinners',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_winner', to='stack.RafflePlayer'),
        ),
        migrations.AddField(
            model_name='raffleplayer',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stack.WeekEndRaffle'),
        ),
        migrations.AddField(
            model_name='raffleplayer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='stack.Event'),
        ),
        migrations.AddField(
            model_name='match',
            name='game_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_date', to='stack.ActiveGame'),
        ),
        migrations.AddField(
            model_name='game',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='stack.Match'),
        ),
        migrations.AddField(
            model_name='game',
            name='slip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slip', to='stack.Slip'),
        ),
    ]
