# Generated by Django 2.2.1 on 2019-07-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0003_remove_team_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='clubs_history',
            field=models.CharField(max_length=2000),
        ),
    ]
