# Generated by Django 2.2.1 on 2019-07-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0005_slip_stake'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
