# Generated by Django 2.2.1 on 2019-08-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0006_slip_is_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekendraffle',
            name='raffle_date',
        ),
        migrations.RemoveField(
            model_name='weekendraffle',
            name='raffle_ending',
        ),
        migrations.AddField(
            model_name='raffleplayer',
            name='raffle_hash',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='weekendraffle',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weekendraffle',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weekendraffle',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
