# Generated by Django 2.2.1 on 2019-08-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0007_auto_20190815_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='even_odd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
