# Generated by Django 2.2.1 on 2019-08-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0008_auto_20190818_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_ending_time',
        ),
        migrations.AddField(
            model_name='match',
            name='resulted',
            field=models.BooleanField(default=False),
        ),
    ]
