# Generated by Django 2.2.1 on 2019-08-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0009_auto_20190818_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='is_smart_user',
            field=models.BooleanField(default=False),
        ),
    ]
