# Generated by Django 2.2.1 on 2019-08-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0010_slip_is_smart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_smart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
