# Generated by Django 2.2.1 on 2019-08-24 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0011_auto_20190819_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='rafflewinners',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
