# Generated by Django 2.2.1 on 2019-09-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0012_rafflewinners_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffleplayer',
            name='should_win',
            field=models.BooleanField(default=True),
        ),
    ]
