# Generated by Django 2.2.1 on 2019-09-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0013_raffleplayer_should_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekendraffle',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
