# Generated by Django 2.2.1 on 2019-09-22 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0014_weekendraffle_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekendraffle',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
