# Generated by Django 2.2.1 on 2019-09-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0015_weekendraffle_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='jackpot_check',
            field=models.BooleanField(default=False),
        ),
    ]
